# Generated by Django 5.1.6 on 2025-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowers/'),
        ),
        migrations.AddField(
            model_name='flower',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
